// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"dwango_ForceWebAudio","status":false,"description":"","parameters":{}},
{"name":"dwango_androidpatch","status":false,"description":"Android Chromeで音が鳴らない問題を解決するプラグイン","parameters":{}},
{"name":"ScreenResolution","status":true,"description":"ゲームスクリーンの解像度を好きなように変更することができます","parameters":{"Screen Width":"816","Screen Height":"459"}},
{"name":"Yami_SkipTitle","status":true,"description":"テストプレイ用にタイトルシーンを飛ばすことができます。","parameters":{}},
{"name":"filters","status":true,"description":"","parameters":{}},
{"name":"StartUpFullScreen","status":true,"description":"フルスクリーンで起動プラグイン","parameters":{"シャットダウン":"Close","フルスクリーンで起動":"フルスクリーンで起動"}},
{"name":"SAN_RendererTypeSelector","status":true,"description":"レンダラータイプセレクター 1.0.0\r\nレンダラータイプを指定するデバッグコードです。","parameters":{"RendererType":"webgl"}}
];
